### ISSUE TITLE
closed

### ISSUE THREAD

**Issue by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [octosavvi/ESPKey#12]
closed

**Comment by aSmig** [comment]
Kantech XSF is used between the card and the card reader. Since ESPKey is installed between the card reader and the door controller, only the wired protocol matters. Looking at images of the P325XSF, I see the only data connections are labeled D0 and D1, which indicates standard Wiegand protocol. ESPKey will almost certainly work with this reader.

**Comment by zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz-z** [comment]
closed
