### ISSUE TITLE
Missing KiCAD libraries

### ISSUE THREAD

**Issue by nuschpl** [octosavvi/ESPKey#14]
Hello
I'm getting to the following when trying to open schematics:
```
The following libraries were not found:
power.lib
device.lib
transistors.lib
conn.lib
linear.lib
regul.lib
74xx.lib
cmos4000.lib
adc-dac.lib
memory.lib
xilinx.lib
microcontrollers.lib
dsp.lib
microchip.lib
analog_switches.lib
motorola.lib
texas.lib
intel.lib
audio.lib
interface.lib
digital-audio.lib
philips.lib
display.lib
cypress.lib
siliconi.lib
opto.lib
atmel.lib
contrib.lib
valves.lib
libraries/Richtek/Richtek.lib
libraries/kicad-ESP8266/ESP8266.lib
```
Are there any references to exact source of those libraries ? And are all those in deed needed(I see mulitple vendors) , if not can those be removed ?

**Comment by aSmig** [comment]
I recommend using the [Schematic PDF](https://github.com/octosavvi/ESPKey/blob/master/hardware/schematic.pdf) rather than trying to open this old dead project in modern Eeschema.

This error looks like a version mismatch issue. KiCad of 7 years ago included most of the listed libraries as default (the two exceptions are Richtek and ESP8266). Why it chose to explicitly list all of those default libraries in the project file is beyond me. None of these library files should be necessary to open the project because all non-standard parts used in the project were automatically duplicated into the ESPKey-cache.lib file.

Sources for reference:
[ESP8266.lib](https://github.com/jdunmire/kicad-ESP8266)
Richtek.lib unknown - maybe I cobbled it together. The only part it contains is already in ESPKey-cache.lib
