### ISSUE TITLE
Comple error for ArduinoJson 6

### ISSUE THREAD

**Issue by dbuggz** [octosavvi/ESPKey#6]
Hi, 
just looking into your ESPKey and when I compile the ESPKey.ino I get:
 
`ESPKey:238:11: error: StaticJsonBuffer is a class from ArduinoJson 5. Please see https://arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
  238 |   StaticJsonBuffer<1024> jsonBuffer;
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~                 `

I've tried a couple of things from their page ( changing the JsonBuffer in line 238 and removing the & in line 239) but am not proficient enough to work all the changes out.

**Comment by aSmig** [comment]
You may find it easier to use the Arduino library manager to downgrade your ArduinoJson rather than updating the code to work with ArduinoJson 6. The last release was compiled with ArduinoJson 5.11 but more recent versions in the 5.x family are likely to work too.

To open the library manager: Sketch -> Include Library -> Manage Libraries...
To downgrade: search for ArduinoJson, click on it, a "Select Version" drop-down box will appear, choose a version and press Install
